name: Docker Image CI

on: [push]

jobs:

  shellcheck:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install shellcheck
        run: |
          scversion="stable"
          wget -qO- "https://storage.googleapis.com/shellcheck/shellcheck-${scversion?}.linux.x86_64.tar.xz" | tar -xJv
          sudo cp "shellcheck-${scversion}/shellcheck" /usr/bin/
          shellcheck --version
      - name: shell check
        run: shellcheck versions/alpine/docker-entrypoint.sh

  build:

    needs: shellcheck

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: docker build --tag scrapedia/privoxy:$(date +%s) --file Dockerfile .
        working-directory: versions/alpine

  container-structure-test:
    
    needs: build
    
    runs-on: ubuntu-latest
    
    steps:
      - name: Container structure test
        run: |
          curl -LO https://storage.googleapis.com/container-structure-test/latest/container-structure-test-linux-amd64 && \
          chmod +x container-structure-test-linux-amd64 && \
          sudo mv container-structure-test-linux-amd64 /usr/local/bin/container-structure-test && \
          container-structure-test --help
